In [1]:
#https://healthdata.gov/resource/anag-cw7u.json

In [2]:
import pandas as pd
import json

In [3]:
import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("healthdata.gov", None)


results = client.get("anag-cw7u", limit=2000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [23]:
results_df

,hospital_pk,collection_week,state,ccn,hospital_name,address,city,zip,hospital_subtype,fips_code,...,total_patients_hospitalized_confirmed_influenza_7_day_sum,icu_patients_confirmed_influenza_7_day_sum,total_patients_hospitalized_confirmed_influenza_and_covid_7_day_sum,previous_day_admission_influenza_confirmed_7_day_sum,previous_week_personnel_covid_vaccinated_doses_administered_7_day,total_personnel_covid_vaccinated_doses_none_7_day,total_personnel_covid_vaccinated_doses_one_7_day,total_personnel_covid_vaccinated_doses_all_7_day,previous_week_patients_covid_vaccinated_doses_one_7_day,previous_week_patients_covid_vaccinated_doses_all_7_day
0,220176,2021-09-03T00:00:00.000,MA,220176,ST VINCENT HOSPITAL,123 SUMMER STREET,WORCESTER,01608,Short Term,25027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,392028,2021-09-03T00:00:00.000,PA,392028,CURAHEALTH PITTSBURGH,7777 STEUBENVILLE PIKE,OAKDALE,15071,Long Term,42003,...,0,0,0,0,0,23,37,36,0,0
2,431323,2021-09-03T00:00:00.000,SD,431323,MONUMENT HEALTH CUSTER HOSPITAL,1220 MONTGOMERY STREET,CUSTER,57730,Critical Access Hospitals,46033,...,0,0,0,0,-999999,79,126,124,37,22
3,100307,2021-09-03T00:00:00.000,FL,100307,ASCENSION ST VINCENT'S SOUTHSIDE,4201 BELFORT RD,JACKSONVILLE,32216,Short Term,12031,...,0,0,0,0,14,384,5,984,0,0
4,180102,2021-09-03T00:00:00.000,KY,180102,LOURDES HOSPITAL,1530 LONE OAK ROAD,PADUCAH,42003,Short Term,21145,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,050468,2021-09-03T00:00:00.000,CA,050468,MEMORIAL HOSPITAL OF GARDENA,1145 W REDONDO BEACH BLVD,GARDENA,90247,Short Term,06037,...,0,0,0,0,92,212,25,476,60,32
1996,230216,2021-09-03T00:00:00.000,MI,230216,MCLAREN PORT HURON,1221 PINE GROVE AVE,PORT HURON,48060,Short Term,26147,...,0,0,0,0,0,0,0,0,0,0
1997,050128,2021-09-03T00:00:00.000,CA,050128,TRI-CITY MEDICAL CENTER,4002 VISTA WAY,OCEANSIDE,92056,Short Term,06073,...,0,0,0,0,30,637,28,1806,30,0
1998,452019,2021-09-03T00:00:00.000,TX,452019,KINDRED HOSPITAL FORT WORTH- MANSFIELD,1802 HIGHWAY 157 NORTH,MANSFIELD,76063,Long Term,48439,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,520207,2021-09-03T00:00:00.000,WI,520207,AURORA MEDICAL CENTER,975 PORT WASHINGTON ROAD,GRAFTON,53024,Short Term,55089,...,NaN,NaN,NaN,NaN,26,374,74,790,0,0

In [22]:
results_df.columns.to_list()

['hospital_pk',
 'collection_week',
 'state',
 'ccn',
 'hospital_name',
 'address',
 'city',
 'zip',
 'hospital_subtype',
 'fips_code',
 'is_metro_micro',
 'total_beds_7_day_avg',
 'all_adult_hospital_beds_7_day_avg',
 'all_adult_hospital_inpatient_beds_7_day_avg',
 'inpatient_beds_used_7_day_avg',
 'all_adult_hospital_inpatient_bed_occupied_7_day_avg',
 'total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg',
 'total_adult_patients_hospitalized_confirmed_covid_7_day_avg',
 'total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg',
 'total_pediatric_patients_hospitalized_confirmed_covid_7_day_avg',
 'inpatient_beds_7_day_avg',
 'total_icu_beds_7_day_avg',
 'total_staffed_adult_icu_beds_7_day_avg',
 'icu_beds_used_7_day_avg',
 'staffed_adult_icu_bed_occupancy_7_day_avg',
 'staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_avg',
 'staffed_icu_adult_patients_confirmed_covid_7_day_avg',
 'total_beds_7_day_sum',
 'all_adult_hospital_beds_7_day_sum',
 'all_adult_hospital_inpatient_beds_7_day_sum',
 'inpatient_beds_used_7_day_sum',
 'all_adult_hospital_inpatient_bed_occupied_7_day_sum',
 'total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum',
 'total_adult_patients_hospitalized_confirmed_covid_7_day_sum',
 'total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum',
 'total_pediatric_patients_hospitalized_confirmed_covid_7_day_sum',
 'inpatient_beds_7_day_sum',
 'total_icu_beds_7_day_sum',
 'total_staffed_adult_icu_beds_7_day_sum',
 'icu_beds_used_7_day_sum',
 'staffed_adult_icu_bed_occupancy_7_day_sum',
 'staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_sum',
 'staffed_icu_adult_patients_confirmed_covid_7_day_sum',
 'total_beds_7_day_coverage',
 'all_adult_hospital_beds_7_day_coverage',
 'all_adult_hospital_inpatient_beds_7_day_coverage',
 'inpatient_beds_used_7_day_coverage',
 'all_adult_hospital_inpatient_bed_occupied_7_day_coverage',
 'total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_coverage',
 'total_adult_patients_hospitalized_confirmed_covid_7_day_coverage',
 'total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_coverage',
 'total_pediatric_patients_hospitalized_confirmed_covid_7_day_coverage',
 'inpatient_beds_7_day_coverage',
 'total_icu_beds_7_day_coverage',
 'total_staffed_adult_icu_beds_7_day_coverage',
 'icu_beds_used_7_day_coverage',
 'staffed_adult_icu_bed_occupancy_7_day_coverage',
 'staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_coverage',
 'staffed_icu_adult_patients_confirmed_covid_7_day_coverage',
 'total_patients_hospitalized_confirmed_influenza_7_day_coverage',
 'icu_patients_confirmed_influenza_7_day_coverage',
 'total_patients_hospitalized_confirmed_influenza_and_covid_7_day_coverage',
 'previous_day_admission_adult_covid_confirmed_7_day_sum',
 'previous_day_admission_adult_covid_confirmed_18_19_7_day_sum',
 'previous_day_admission_adult_covid_confirmed_20_29_7_day_sum',
 'previous_day_admission_adult_covid_confirmed_30_39_7_day_sum',
 'previous_day_admission_adult_covid_confirmed_40_49_7_day_sum',
 'previous_day_admission_adult_covid_confirmed_50',
 'previous_day_admission_adult_covid_confirmed_60',
 'previous_day_admission_adult_covid_confirmed_70',
 'previous_day_admission_adult_covid_confirmed_80',
 'previous_day_admission_adult_covid_confirmed_unknown_7_day_sum',
 'previous_day_admission_pediatric_covid_confirmed_7_day_sum',
 'previous_day_covid_ed_visits_7_day_sum',
 'previous_day_admission_adult_covid_suspected_7_day_sum',
 'previous_day_admission_adult_covid_suspected_18',
 'previous_day_admission_adult_covid_suspected_20',
 'previous_day_admission_adult_covid_suspected_30',
 'previous_day_admission_adult_covid_suspected_40',
 'previous_day_admission_adult_covid_suspected_50',
 'previous_day_admission_adult_covid_suspected_60',
 'previous_day_admission_adult_covid_suspected_70_79_7_day_sum',
 'previous_day_admission_adult_covid_suspected_80',
 'previous_day_admission_adult_covid_suspected_unknown_7_day_sum',
 'previous_day_admission_pediatric_covid_suspected_7_day_sum',
 'previous_day_total_ed_visits_7_day_sum',
 'geocoded_hospital_address',
 'hhs_ids',
 'previous_day_admission_adult_covid_confirmed_7_day_coverage',
 'previous_day_admission_pediatric_covid_confirmed_7_day_coverage',
 'previous_day_admission_adult_covid_suspected_7_day_coverage',
 'previous_day_admission_pediatric_covid_suspected_7_day_coverage',
 'is_corrected',
 ':@computed_region_pqdx_y6mm',
 'total_patients_hospitalized_confirmed_influenza_7_day_avg',
 'icu_patients_confirmed_influenza_7_day_avg',
 'total_patients_hospitalized_confirmed_influenza_and_covid_7_day_avg',
 'total_patients_hospitalized_confirmed_influenza_7_day_sum',
 'icu_patients_confirmed_influenza_7_day_sum',
 'total_patients_hospitalized_confirmed_influenza_and_covid_7_day_sum',
 'previous_day_admission_influenza_confirmed_7_day_sum',
 'previous_week_personnel_covid_vaccinated_doses_administered_7_day',
 'total_personnel_covid_vaccinated_doses_none_7_day',
 'total_personnel_covid_vaccinated_doses_one_7_day',
 'total_personnel_covid_vaccinated_doses_all_7_day',
 'previous_week_patients_covid_vaccinated_doses_one_7_day',
 'previous_week_patients_covid_vaccinated_doses_all_7_day']

In [6]:
#on average beds available
hospital_data = results_df[['state','hospital_name','address','city','zip','total_beds_7_day_sum','inpatient_beds_used_7_day_sum','icu_beds_used_7_day_sum','total_icu_beds_7_day_sum',]]

In [7]:
hospital_data

,state,hospital_name,address,city,zip,total_beds_7_day_sum,inpatient_beds_used_7_day_sum,icu_beds_used_7_day_sum,total_icu_beds_7_day_sum
0,MA,ST VINCENT HOSPITAL,123 SUMMER STREET,WORCESTER,01608,1701,1180,152,196
1,PA,CURAHEALTH PITTSBURGH,7777 STEUBENVILLE PIKE,OAKDALE,15071,105,88,0,0
2,SD,MONUMENT HEALTH CUSTER HOSPITAL,1220 MONTGOMERY STREET,CUSTER,57730,77,47,0,0
3,FL,ASCENSION ST VINCENT'S SOUTHSIDE,4201 BELFORT RD,JACKSONVILLE,32216,1939,1068,183,105
4,KY,LOURDES HOSPITAL,1530 LONE OAK ROAD,PADUCAH,42003,2506,820,164,165
...,...,...,...,...,...,...,...,...,...
1995,CA,MEMORIAL HOSPITAL OF GARDENA,1145 W REDONDO BEACH BLVD,GARDENA,90247,860,686,52,50
1996,MI,MCLAREN PORT HURON,1221 PINE GROVE AVE,PORT HURON,48060,1386,1148,80,126
1997,CA,TRI-CITY MEDICAL CENTER,4002 VISTA WAY,OCEANSIDE,92056,1946,1200,154,315
1998,TX,KINDRED HOSPITAL FORT WORTH- MANSFIELD,1802 HIGHWAY 157 NORTH,MANSFIELD,76063,46,45,0,0
1999,WI,AURORA MEDICAL CENTER,975 PORT WASHINGTON ROAD,GRAFTON,53024,1218,748,210,336

In [8]:
hospital_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   state                          2000 non-null   object
 1   hospital_name                  2000 non-null   object
 2   address                        1999 non-null   object
 3   city                           1999 non-null   object
 4   zip                            2000 non-null   object
 5   total_beds_7_day_sum           2000 non-null   object
 6   inpatient_beds_used_7_day_sum  2000 non-null   object
 7   icu_beds_used_7_day_sum        2000 non-null   object
 8   total_icu_beds_7_day_sum       2000 non-null   object
dtypes: object(9)
memory usage: 140.8+ KB

In [9]:
data = hospital_data

In [10]:
data

,state,hospital_name,address,city,zip,total_beds_7_day_sum,inpatient_beds_used_7_day_sum,icu_beds_used_7_day_sum,total_icu_beds_7_day_sum
0,MA,ST VINCENT HOSPITAL,123 SUMMER STREET,WORCESTER,01608,1701,1180,152,196
1,PA,CURAHEALTH PITTSBURGH,7777 STEUBENVILLE PIKE,OAKDALE,15071,105,88,0,0
2,SD,MONUMENT HEALTH CUSTER HOSPITAL,1220 MONTGOMERY STREET,CUSTER,57730,77,47,0,0
3,FL,ASCENSION ST VINCENT'S SOUTHSIDE,4201 BELFORT RD,JACKSONVILLE,32216,1939,1068,183,105
4,KY,LOURDES HOSPITAL,1530 LONE OAK ROAD,PADUCAH,42003,2506,820,164,165
...,...,...,...,...,...,...,...,...,...
1995,CA,MEMORIAL HOSPITAL OF GARDENA,1145 W REDONDO BEACH BLVD,GARDENA,90247,860,686,52,50
1996,MI,MCLAREN PORT HURON,1221 PINE GROVE AVE,PORT HURON,48060,1386,1148,80,126
1997,CA,TRI-CITY MEDICAL CENTER,4002 VISTA WAY,OCEANSIDE,92056,1946,1200,154,315
1998,TX,KINDRED HOSPITAL FORT WORTH- MANSFIELD,1802 HIGHWAY 157 NORTH,MANSFIELD,76063,46,45,0,0
1999,WI,AURORA MEDICAL CENTER,975 PORT WASHINGTON ROAD,GRAFTON,53024,1218,748,210,336

In [21]:
final_data = data.dropna()

In [24]:
final_data
final_data = final_data.rename({'total_beds_7_day_sum': 'tb_sum', 'inpatient_beds_used_7_day_sum': 'ib_sum' ,'icu_beds_used_7_day_sum': 'icub_sum' ,'total_icu_beds_7_day_sum': 'total_icub_sum'  }, axis=1)

In [25]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1999 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           1999 non-null   object
 1   hospital_name   1999 non-null   object
 2   address         1999 non-null   object
 3   city            1999 non-null   object
 4   zip             1999 non-null   object
 5   tb_sum          1999 non-null   object
 6   ib_sum          1999 non-null   object
 7   icub_sum        1999 non-null   object
 8   total_icub_sum  1999 non-null   object
dtypes: object(9)
memory usage: 156.2+ KB

In [26]:
final_data = final_data.rename({'total_beds_7_day_sum': 'tb_sum', 'inpatient_beds_used_7_day_sum': 'ib_sum' ,'icu_beds_used_7_day_sum': 'icub_sum' ,'total_icu_beds_7_day_sum': 'ticub_sum'  }, axis=1)

In [27]:
final_data

,state,hospital_name,address,city,zip,tb_sum,ib_sum,icub_sum,total_icub_sum
0,MA,ST VINCENT HOSPITAL,123 SUMMER STREET,WORCESTER,01608,1701,1180,152,196
1,PA,CURAHEALTH PITTSBURGH,7777 STEUBENVILLE PIKE,OAKDALE,15071,105,88,0,0
2,SD,MONUMENT HEALTH CUSTER HOSPITAL,1220 MONTGOMERY STREET,CUSTER,57730,77,47,0,0
3,FL,ASCENSION ST VINCENT'S SOUTHSIDE,4201 BELFORT RD,JACKSONVILLE,32216,1939,1068,183,105
4,KY,LOURDES HOSPITAL,1530 LONE OAK ROAD,PADUCAH,42003,2506,820,164,165
...,...,...,...,...,...,...,...,...,...
1995,CA,MEMORIAL HOSPITAL OF GARDENA,1145 W REDONDO BEACH BLVD,GARDENA,90247,860,686,52,50
1996,MI,MCLAREN PORT HURON,1221 PINE GROVE AVE,PORT HURON,48060,1386,1148,80,126
1997,CA,TRI-CITY MEDICAL CENTER,4002 VISTA WAY,OCEANSIDE,92056,1946,1200,154,315
1998,TX,KINDRED HOSPITAL FORT WORTH- MANSFIELD,1802 HIGHWAY 157 NORTH,MANSFIELD,76063,46,45,0,0
1999,WI,AURORA MEDICAL CENTER,975 PORT WASHINGTON ROAD,GRAFTON,53024,1218,748,210,336

In [36]:
final_data.to_csv('hospital_data.csv')

In [39]:
import os

In [41]:
os.getcwd()

'C:\\Users\\Okyere\\Covid19 Project\\covid-19-image-classification'